services:
  kitchen-ops:
    build: .
    container_name: kitchen_ops
    env_file: .env
    # The volumes below are examples. Users must update them to match their setup.
    volumes:
      - ./data:/app/data:z # For SQLite users (Accelerator Mode): Mount the folder containing mealie.db
    restart: no
